services:
  environment:
    image: mcr.microsoft.com/devcontainers/base:debian
    volumes:
      - type: bind
        source: ..
        target: /workspace
        read_only: false
    tty: true
    stdin_open: true
