name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main, development]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Inyectar Node.js desde archivo de configuración
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false # o true según la necesidad de la pipeline
